name: Deploy to "stokhastik.xyz"

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Deploy with rsync
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

          sshpass -p "${{ secrets.PASSWORD }}" \
            rsync -avz --delete \
            -e "ssh -p ${{ secrets.PORT }} -o StrictHostKeyChecking=no" \
            --exclude='.env' \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='.next' \
            --exclude='.vscode' \
            --exclude='node_modules' \
            --exclude='out' \
            --exclude='data' \
            --exclude='.snap' \
            ./ \
            ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/srv/customer/sites/stokhastik.xyz/
